directory: ~/music/Library/
library: ~/music/beets_db.blb
plugins:
  - chroma
  - fetchart
  - embedart
  - fromfilename
  - lastgenre
  - mpdupdate
  - duplicates
  - edit
  - smartplaylist

import:
  move: yes

fetchart:
  auto: yes
  sources: amazon filesystem coverart albumart

smartplaylist:
  relative_to: ~/music/
  playlist_dir: ~/music/playlists/
  playlists:
    - name: new.m3u
      query: 'added:2020'

embedart:
  auto: yes
  remove_art_file: yes

mpd:
    host: localhost
    port: 6600
