position: top
height: 30
popup_gap: 5
popup_autohide: false

start:
  - type: workspaces

  - type: volume
    format: "{icon} {percentage}%"
    max_volume: 130

  - type: music
    player_type: mpris
    format: "{artist}  {title}"
    truncate:
      mode: end
      max_length: 40

center:
  - type: clock
    format: "%a %d %b  %H:%M"
    justify: center

end:
  - type: sys_info
    format:
      - " {temp_c:k10temp-Tctl}°"
      - "󰾲 {temp_c:amdgpu-edge}°"
    interval:
      temps: 5

  - type: bluetooth

  - type: custom
    bar:
      - type: label
        label: "{{5000:~/.local/bin/ps4-controller}}"

  - type: custom
    bar:
      - type: button
        label: ""
        on_click: popup:toggle
    popup:
      - type: box
        orientation: vertical
        widgets:
          - type: button
            class: menu-item
            on_click: "!~/.local/bin/sway-monitor HDMI-A-2 toggle"
            widgets:
              - type: box
                orientation: horizontal
                widgets:
                  - type: label
                    class: menu-item-icon
                    label: "{{5000:~/.local/bin/sway-monitor HDMI-A-2}}"
                  - type: label
                    class: menu-item-text
                    label: "Toggle monitor output"
          - type: button
            class: menu-item
            on_click: "!~/.local/bin/sway-monitor DP-1 toggle"
            widgets:
              - type: box
                orientation: horizontal
                widgets:
                  - type: label
                    class: menu-item-icon
                    label: "{{5000:~/.local/bin/sway-monitor DP-1}}"
                  - type: label
                    class: menu-item-text
                    label: "Toggle TV output"
          - type: button
            class: menu-item
            on_click: "!~/.local/bin/swayidle-toggle toggle"
            widgets:
              - type: box
                orientation: horizontal
                widgets:
                  - type: label
                    class: menu-item-icon
                    label: "{{10000:~/.local/bin/swayidle-toggle icon}}"
                  - type: label
                    class: menu-item-text
                    label: "Toggle auto sleep"
          - type: button
            class: menu-item
            on_click: "!~/.local/bin/tv-remote"
            widgets:
              - type: box
                orientation: horizontal
                widgets:
                  - type: label
                    class: menu-item-icon
                    label: "󰻅"
                  - type: label
                    class: menu-item-text
                    label: "TV ON/OFF"
          - type: button
            class: menu-item
            on_click: "!steam"
            widgets:
              - type: box
                orientation: horizontal
                widgets:
                  - type: label
                    class: menu-item-icon
                    label: ""
                  - type: label
                    class: menu-item-text
                    label: "Launch Steam"

  - type: custom
    bar:
      - type: button
        label: "⏻"
        on_click: "popup:toggle"
    popup:
      - type: box
        orientation: vertical
        widgets:
          - type: button
            label: "Suspend"
            on_click: "!systemctl suspend"
          - type: button
            label: "Reboot"
            on_click: "!reboot"
          - type: button
            label: "Shutdown"
            on_click: "!shutdown now"
