#!/bin/sh

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CONFIG_DIR=$XDG_CONFIG_HOME

FONTDIR="$HOME/.local/share/fonts"
RESOURCES="$HOME/.Xresources"

# Fonts
xset +fp "$FONTDIR"

# Load xresources
[ -f "$RESOURCES" ] && xrdb -load "$RESOURCES"

# use right alt as compose key and caps lock as control
setxkbmap -option compose:ralt -option ctrl:nocaps

# Super fast typing
xset r rate 200 44

# Scaling on XPS 13
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
export ELM_SCALE=1.5

systemctl --user import-environment DISPLAY XAUTHORITY
if command -v dbus-update-activation-environment >/dev/null 2>&1; then
	dbus-update-activation-environment DISPLAY XAUTHORITY
fi

xrandr --dpi 166
pgrep i3 || exec i3
