#! /bin/bash

export XDG_CONFIG_HOME=$HOME/.config

FONTDIR="$HOME/.local/share/fonts"
RESOURCES="$HOME/.Xresources"
RESOURCES_DIR="$HOME/.Xresources.d"

# Fonts
xset +fp "$FONTDIR"

# Load xresources
if [ -f "$RESOURCES" ] && [ -d "$RESOURCES_DIR" ]; then
  xrdb -I"$RESOURCES_DIR" -load "$RESOURCES"
fi

# use right alt as compose key and caps lock as control
setxkbmap -option compose:ralt -option ctrl:nocaps

# Super fast typing
xset r rate 200 44

# Scaling on XPS 13
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
export ELM_SCALE=1.5

# Autolock on lid close
if ! pgrep -x xss-lock > /dev/null
then
    xss-lock -- $HOME/.local/i3lock-fancy/lock &
fi

# Start nm-applet
if ! pgrep -x nm-applet > /dev/null
then
    nm-applet &
fi

# execute awesome
if ! pgrep -x awesome > /dev/null
then
    exec awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr
fi
