#!/bin/sh

export XDG_CONFIG_HOME=$HOME/.config

FONTDIR="$HOME/.local/share/fonts"
RESOURCES="$HOME/.Xresources"
RESOURCES_DIR="$HOME/.Xresources.d"

# Fonts
xset +fp "$FONTDIR"

# Load xresources
if [ -f "$RESOURCES" ] && [ -d "$RESOURCES_DIR" ]; then
	xrdb -I"$RESOURCES_DIR" -load "$RESOURCES"
fi

# use right alt as compose key and caps lock as control
setxkbmap -option compose:ralt -option ctrl:nocaps

# Super fast typing
xset r rate 200 44

# Scaling on XPS 13
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
export ELM_SCALE=1.5

# start the xsession target
if ! systemctl --user is-active xsession.target >/dev/null 2>/dev/null
then
	systemctl --user import-environment DISPLAY XAUTHORITY
	systemctl --user start xsession.target
fi

# execute i3
if ! pgrep -x i3 > /dev/null
then
	systemctl --user start graphical.target
	exec i3
fi
