#!/bin/sh

set -e

# shellcheck source=/dev/null
. "$HOME/.dotfiles/builds/lib"

git_url=https://github.com/muennich/sxiv.git
git_version=v24

_install() {
	_git_clone "$git_url" "$git_version" "$BUILD_DIR_PATH"

	_log "Copying the config file"
	cp "$BUILD_PROJECT_PATH/config.def.h" "$BUILD_DIR_PATH/config.h"

	_log "Building sxiv"
	make -C "$BUILD_DIR_PATH"
	sudo make -C "$BUILD_DIR_PATH" install
}

_uninstall() {
	sudo make -C "$BUILD_DIR_PATH" uninstall
}
