#!/bin/bash

# Required folders
mkdir -p $HOME/.config
mkdir -p $HOME/.local/bin

# Neovim
if [ ! -L $HOME/.config/nvim ]; then
    ln -s $HOME/.vim $HOME/.config/nvim
fi
if [ ! -L $HOME/.vim/init.vim ]; then
    ln -s $HOME/.vimrc $HOME/.vim/init.vim
fi

# Install vim plugins
if type nvim 2>/dev/null; then
    nvim -u "$HOME/.vim/plugins.vim" +PlugInstall +PlugClean! +qa
else
    vim -u "$HOME/.vim/plugins.vim" +PlugInstall +PlugClean! +qa
fi

# Create the required files for mutt
if [ -L $HOME/.mutt ]; then
    mkdir -p ~/.mutt/cache
    mkdir -p ~/.mutt/tmp
    touch ~/.mutt/certificates
fi

# Create the required directory for mpd
if [ -L $HOME/.mpdconf ]; then
    mkdir -p ~/.mpd
fi

# z
touch ~/.z
