#!/bin/sh

# Required folders
mkdir -p "$HOME/.config"
mkdir -p "$HOME/.local/bin"

# Install vim plugins
if type vim >/dev/null 2>/dev/null; then
    vim --not-a-term +PlugInstall +PlugClean! +qa
fi

# Install tmux plugins
tmux_plugins="$HOME/.tmux/plugins/"
[ -d "$tmux_plugins/tmux-copycat" ] || "$tmux_plugins/tpm/bin/install_plugins"

# Create the required files for mutt
[ -L "$HOME/.mutt" ] && {
    mkdir -p "$HOME/.mutt/cache"
    mkdir -p "$HOME/.mutt/tmp"
    touch "$HOME/.mutt/certificates"
}

# Create the required directory for mpd
[ -L "$HOME/.mpdconf" ] && mkdir -p "$HOME/.mpd"

# z
touch "$HOME/.z"
