#!/bin/sh

# Required folders
mkdir -p "$HOME/.config"
mkdir -p "$HOME/.local/bin"

# Neovim
[ -L "$HOME/.config/nvim" ]  || ln -s "$HOME/.vim" "$HOME/.config/nvim"
[ -L "$HOME/.vim/init.vim" ] || ln -s "$HOME/.vimrc" "$HOME/.vim/init.vim"

# Install vim plugins
plugins_file="$HOME/.vim/plugins.vim"
if type nvim >/dev/null 2>/dev/null; then
    nvim -u "$plugins_file" +PlugInstall +PlugClean! +qa
else
    vim --not-a-term -u "$plugins_file" +PlugInstall +PlugClean! +qa
fi

# Install tmux plugins
"$HOME/.tmux/plugins/tpm/bin/install_plugins"

# Create the required files for mutt
[ -L "$HOME/.mutt" ] && {
    mkdir -p "$HOME/.mutt/cache"
    mkdir -p "$HOME/.mutt/tmp"
    touch "$HOME/.mutt/certificates"
}

# Create the required directory for mpd
[ -L "$HOME/.mpdconf" ] && mkdir -p "$HOME/.mpd"

# z
touch "$HOME/.z"
