fps
fps_color_change
frame_timing=0
present_mode
vulkan_driver

cpu_stats
cpu_power
cpu_temp

gpu_stats
gpu_core_clock
gpu_mem_clock
gpu_power
gpu_temp
gpu_mem_temp
gpu_list=0
gpu_fan

ram
vram

device_battery=gamepad
throttling_status
wine
winesync
resolution

toggle_hud=Shift_L+F6
position=top-right
