[preset 1]
legacy_layout=0
fps_only=1
cpu_stats=0
gpu_stats=0
frametime=0

[preset 2]
legacy_layout=0
horizontal
fps
frametime
gpu_stats
gpu_temp
cpu_stats
cpu_temp
vram
ram
position=top-left
background_alpha=0.35

[preset 3]
legacy_layout=0
fps
frametime
frame_timing
gpu_stats
gpu_temp
gpu_power
gpu_core_clock
gpu_mem_clock
cpu_stats
cpu_temp
cpu_power
vram
ram
wine
engine_version
resolution
refresh_rate

[preset 4]
legacy_layout=0
full
