fps
frame_timing=0

ram
vram
cpu_power
cpu_temp
gpu_power
gpu_temp
gpu_mem_temp
gpu_list=0,1
gpu_fan

device_battery=gamepad
throttling_status
wine
winesync
resolution

toggle_hud=Shift_L+F6
position=top-right
