#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

export CUSTOM_BUILD_DIR=$HOME/dev/build
[ -d "$CUSTOM_BUILD_DIR" ] || mkdir -p "$CUSTOM_BUILD_DIR"

export PROJECTS_DIR=$HOME/.dotfiles/builds/builds.d

_log() {
    printf "\e[36m-->\e[39m \e[92m%s\e[39m\n" "$@"
}

_check_argument() {
	[ "$1" ] && return 0

	_log "missing argument"
	return 1
}

_git_clone() {
	url=$1
	version=$2
	path=$3
	_check_argument "$url"
	_check_argument "$path"
	_check_argument "$version"

	if [ -d "$path/.git" ]; then
		_log "Updating repo $path"
		git -C "$path" fetch
	else
		_log "Cloning $url"
		git clone "$url" "$path"
	fi

	_log "Resetting repository to $version"
	git -C "$path" reset --hard "$version"
	git -C "$path" clean -fd
}
