#!/bin/bash

set -e

# shellcheck source=/dev/null
. "$HOME/.dotfiles/builds/lib"

git_url="https://github.com/neovim/neovim.git"
git_version="v0.3.0"

_install() {
	_git_clone "$git_url" "$git_version" "$BUILD_DIR_PATH"
	_log "not implemented"

	# Debian stuff, let's work on this later
	# # Install dependencies
	# sudo apt update
	# sudo apt install -y libtool libtool-bin autoconf automake cmake g++ pkg-config unzip

	# # Make
	# rm -rf "$BUILD_DIR/build"
	# make clean
	# make CMAKE_BUILD_TYPE=Release
	# # Make install
	# sudo make install
}

_uninstall() {
	_log "not implemented"
}
