wireplumber.settings = {
  link.default.audio.sink.follow = true
  link.default.audio.sink.move = true
}

monitor.bluez.rules = [
  {
    matches = [
      { node.name = "bluez_output.AC_BF_71_E7_B2_55.1" }
    ]
    actions = {
      update-props = {
        priority.session = 1000
        priority.driver = 1000
        node.autoconnect = true
        device.intended-roles = "multimedia"
      }
    }
  }
]

monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_output.pci-0000_03_00.1.hdmi-stereo-extra4" }  # TV HDMI
    ]
    actions = {
      update-props = {
        priority.session = 900
        priority.driver = 900
        node.autoconnect = true
      }
    }
  },
  {
    matches = [
      { node.name = "alsa_output.pci-0000_03_00.1.hdmi-stereo-extra2" }  # Monitor HDMI
    ]
    actions = {
      update-props = {
        priority.session = 800
        priority.driver = 800
        node.autoconnect = true
      }
    }
  }
]
