#!/bin/bash

set -e

git_url="https://github.com/neomutt/neomutt.git"
git_version="20220429"

_gpkg_install() {
	_gpkg_git_clone "$git_url" "$git_version" "$GPKG_BUILD_DIR/$GPKG_PKG_NAME"

	_gpkg_configure --lmdb --disable-nls --disable-pgp --disable-idn --disable-doc

	_gpkg_make clean
	_gpkg_make
	_gpkg_make install
}

_gpkg_uninstall() {
	_gpkg_make uninstall
}
