#!/bin/bash

set -e

git_url="https://github.com/neomutt/neomutt.git"
git_version="neomutt-20180716"

_gpkg_install() {
	_gpkg_git_clone "$git_url" "$git_version" "$GPKG_BUILD_DIR/$GPKG_PKG_NAME"

	(cd "$GPKG_BUILD_DIR/$GPKG_PKG_NAME" && \
		./configure \
		--tokyocabinet \
		--disable-doc \
		--sasl \
		--quiet \
	)

	_gpkg_make clean
	_gpkg_make
	_gpkg_make install
}

_gpkg_uninstall() {
	_gpkg_make uninstall
}
