#!/bin/bash

set -e

# shellcheck source=/dev/null
. "$HOME/.dotfiles/builds/lib"

git_url="https://github.com/neomutt/neomutt.git"
git_version="neomutt-20180716"

_install() {
	_git_clone "$git_url" "$git_version" "$BUILD_DIR_PATH"

	(cd "$BUILD_DIR_PATH" && \
		./configure \
		--disable-doc \
		--tokyocabinet \
		--sasl \
	)

	make -C "$BUILD_DIR_PATH" clean
	make -C "$BUILD_DIR_PATH"
}

_uninstall() {
	_log "not implemented"
}
